version: "3.9"

services:
    resume_maker_ai_agent:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: resume_maker_ai_agent
        ports:
            - "7860:7860"
        volumes:
            - .:/app
        environment:
        - PROVIDER=${PROVIDER}
        - MODEL=${MODEL}
        - EMBEDDER=${EMBEDDER}
        - GEMINI_API_KEY=${GEMINI_API_KEY}
        - GOOGLE_API_KEY=${GOOGLE_API_KEY}
        - SERPER_API_KEY=${SERPER_API_KEY}
        command: >
            resume_maker_ai_agent
