name: Test, check and build pipeline

on:
    push:
        branches:
            - main
    pull_request:
        types: [opened, synchronize, reopened, ready_for_review]

jobs:
    quality:
        runs-on: ubuntu-latest
        steps:
            - name: Check out
              uses: actions/checkout@v4

            - uses: actions/cache@v4
              with:
                  path: ~/.cache/pre-commit
                  key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}

            - name: Set up the environment
              uses: ./.github/actions/setup-poetry-env

            - name: Run checks
              run: make lint

    build:
        runs-on: ubuntu-latest
        needs: [quality]
        strategy:
            matrix:
                python-version: ["3.12"]
            fail-fast: false
        defaults:
            run:
                shell: bash
        steps:
            - name: Check out
              uses: actions/checkout@v4

            - name: Set up the environment
              uses: ./.github/actions/setup-poetry-env
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Build
              run: make bake

    check-docs:
        runs-on: ubuntu-latest
        steps:
            - name: Check out
              uses: actions/checkout@v4

            - name: Set up the environment
              uses: ./.github/actions/setup-poetry-env

            - name: Check if documentation can be built
              run: poetry run mkdocs build -s
